# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHMoHPUXDDAJXHB-3eZRnlxD2lMX1n9d
"""

import pandas as pd

df_fear_greed = pd.read_csv("/content/fear_greed_index.csv")
df_historical_data = pd.read_csv("/content/historical_data.csv")

df_fear_greed.sample(n=5)
df_fear_greed.info()

df_historical_data.sample(n=5)
df_historical_data.info()

df_historical_data['Timestamp IST'] = pd.to_datetime(df_historical_data["Timestamp IST"], format="%d-%m-%Y %H:%M")
df_historical_data['date'] = df_historical_data['Timestamp IST'].dt.date

df_historical_data['Timestamp IST'].dt.year.unique()

df_fear_greed['date'] = pd.to_datetime(df_fear_greed['date'])

df_fear_greed = df_fear_greed[
    df_fear_greed['date'].dt.year.isin([2023, 2024, 2025])
]

df_fear_greed

df_historical_data['Closed PnL'] = pd.to_numeric(df_historical_data['Closed PnL'])
df_historical_data['Size USD'] = pd.to_numeric(df_historical_data['Size USD'])

daily_trade_summary = df_historical_data.groupby('date').agg({
    'Closed PnL': 'sum',
    'Size USD': 'sum',
    'Account': 'nunique'
}).reset_index().rename(columns={
    'Closed PnL': 'total_pnl',
    'Size USD': 'total_volume_usd',
    'Account': 'unique_traders'
})

daily_trade_summary.sample(n=5)

df_fear_greed['date'] = pd.to_datetime(df_fear_greed['date']).dt.date

performance_and_market_sentiment_merged_df = pd.merge(daily_trade_summary, df_fear_greed[['date', 'value', 'classification']], on='date', how='left')

performance_and_market_sentiment_merged_df

"""Source 1:"""

correlation_matrix_of_performance_and_market_sentiment = performance_and_market_sentiment_merged_df[['total_pnl', 'total_volume_usd', 'unique_traders', 'value']].corr()

print(correlation_matrix_of_performance_and_market_sentiment)

"""Source 2:"""

df_historical_data['Side_encoded'] = df_historical_data['Side'].str.upper().map({'BUY': 1, 'SELL': 0})

df_historical_data['Crossed_encoded'] = df_historical_data['Crossed'].astype(str).str.upper().map({'TRUE': 1, 'FALSE': 0})

hidden_insights1_merged = pd.merge(
    df_historical_data[['Crossed_encoded', 'date', 'Side_encoded', 'Size USD', 'Closed PnL']],
    df_fear_greed[['date', 'value', 'classification']],
    on='date',
    how='left'
)

hidden_insights1_merged = hidden_insights1_merged.dropna()

deeper_insight_on_sentiment_and_pl = hidden_insights1_merged.groupby('classification').agg({
    'Closed PnL': 'mean',
    'Size USD': 'mean',
}).reset_index().rename(columns={
    'Closed PnL': 'avg_pnl',
    'Size USD': 'avg_volume_usd',
})

deeper_insight_on_sentiment_and_pl

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
fig, ax1 = plt.subplots(figsize=(12, 6))

x = deeper_insight_on_sentiment_and_pl['classification']
x_pos = range(len(x))

color1 = 'tab:blue'
ax1.set_xlabel('Market Sentiment Classification')
ax1.set_ylabel('Avg. PnL', color=color1)
ax1.bar(x_pos, deeper_insight_on_sentiment_and_pl['avg_pnl'], color=color1, width=0.4, label='Avg. PnL')
ax1.tick_params(axis='y', labelcolor=color1)

ax2 = ax1.twinx()
color2 = 'tab:red'
ax2.set_ylabel('Avg. Volume USD', color=color2)
ax2.bar([p + 0.4 for p in x_pos], deeper_insight_on_sentiment_and_pl['avg_volume_usd'], color=color2, width=0.4, label='Avg. Volume')
ax2.tick_params(axis='y', labelcolor=color2)

ax1.set_xticks([p + 0.2 for p in x_pos])
ax1.set_xticklabels(x)

plt.title('Avg. PnL and Avg. Volume by Market Sentiment')

plt.tight_layout()
plt.show()

"""Summary of analysis:

The negative correlation between value(Market sentiments) and total_pnl total_volume_usd, unique_traders tells that trading participation increases significantly with slight increase in trader performance when market sentiment is more fearful.

The bar chart gives even clear insight of how market sentiment signficantly effects participation and p&l.

key insights:

1. On extreme greed days, average volume traded is the lowest but average profit is the highest

2. On fear days average volume traded is highest but average pnl is average.
"""